// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGf5Wq5RPcKEnK6wKRSslmYLYV9wOJwM',
    appId: '1:563434375741:android:5779d59e703378893ef854',
    messagingSenderId: '563434375741',
    projectId: 'flutterapp-2ddee',
    storageBucket: 'flutterapp-2ddee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzrfSMoVfQijghFvu6Q4VSOYXPEP5Ut8',
    appId: '1:563434375741:ios:4f5298747cd8f9c73ef854',
    messagingSenderId: '563434375741',
    projectId: 'flutterapp-2ddee',
    storageBucket: 'flutterapp-2ddee.appspot.com',
    androidClientId: '563434375741-4mvn7cp5bujnclmch50v17jfp6ajbea8.apps.googleusercontent.com',
    iosClientId: '563434375741-b4lrjr5cc5bsh4j6mo2ehluba7fp8u2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterppx',
  );
}
